### ISSUE TITLE
Use of Environment Variables MYSQL_DATABASE - has no effect

### ISSUE THREAD

**Issue by fkaminski** [cytopia/devilbox#448] opened 2018-12-28 17:15 UTC
#### ISSUE TYPE

 - Feature request

#### SUMMARY
I am using the "docker-volumes" branch with "Docker Toolbox v18.09.0" - 
tested with Windows 7/10 Home. 

The "mysql-5.7" Server Image is set in the ".env" file.

For the mysql service the MYSQL_ROOT_PASSWORD is already in use.
I have tried to set the MYSQL_DATABASE variable in the docker-compose.yml for testing purpose like:

```
mysql:
  environment:
    - MYSQL_DATABASE=db_devilbox
```
to create a default database on start, 
so i do not need to create a database manually - see:

https://hub.docker.com/_/mysql
https://hub.docker.com/_/mariadb

Unfortunately, this has no effect at all.
When i start the container with "docker-compose up -d httpd php mysql" 
there is no database "db_devilbox" created - checked via phpMyAdmin.

#### Goal

Use of the MYSQL_DATABASE variable in ".env" / "docker-compose.yml" for the mysql service to create a default database on container/service start.

**Comment by fkaminski** [comment] 2018-12-28 18:50
Think that the variable is just not present in the provided images:
( sorry for my english )

https://github.com/cytopia/docker-mysql-5.7
https://github.com/cytopia/docker-mariadb-10.3

compared to the original mysql image on "Docker Hub" ...

**Comment by cytopia** [comment] 2018-12-28 18:52
Yes, by the time I've done the initial work for the Devilbox, [PerconaDB](https://hub.docker.com/_/percona/) was not yet available as an official Docker image.

As it is now, it is time to move MySQL, MariaDB and PerconaDB to official images. I first need to ensure that they do offer all the currently implemented functionality and have the same sets of injectable variable names,

**Comment by fkaminski** [comment] 2018-12-28 19:07
I see - thanks and greetings form Bremen to Berlin ...

**Comment by cytopia** [comment] 2019-01-02 09:09
I had a look at all three Docker images (MySQL, MariaDB and PerconaDB), they are all built the same way and use the same set of Volumes and Variables.

However I will have to create my own Docker Images out of those, simply by the way the tags are organized as I am unable to do something like this:
```bash
#MYSQL_SERVER=mysql:5.5
#MYSQL_SERVER=mysql:5.6
#MYSQL_SERVER=mysql:5.7
#MYSQL_SERVER=mysql:8.0
#MYSQL_SERVER=mariadb:5.5
#MYSQL_SERVER=mariadb:10.0
#MYSQL_SERVER=mariadb:10.1
#MYSQL_SERVER=mariadb:10.2
MYSQL_SERVER=mariadb:10.3
#MYSQL_SERVER=percona:5.5
#MYSQL_SERVER=percona:5.6
#MYSQL_SERVER=percona:5.7
```

The issue is with the **`:`** (colon) in the name, which will be invalid for Docker Compose variables. So I will simply copy all of them to a single repository and push them by the following TAG structure:
```bash
# Repository: devilbox/mysql
# Example Tag: percona-5.6

# Env file then as currently:
#MYSQL_SERVER=mysql-5.5
#MYSQL_SERVER=mysql-5.6
#MYSQL_SERVER=mysql-5.7
#MYSQL_SERVER=mysql-8.0
#MYSQL_SERVER=mariadb-5.5
#MYSQL_SERVER=mariadb-10.0
#MYSQL_SERVER=mariadb-10.1
#MYSQL_SERVER=mariadb-10.2
MYSQL_SERVER=mariadb-10.3
#MYSQL_SERVER=percona-5.5
#MYSQL_SERVER=percona-5.6
#MYSQL_SERVER=percona-5.7
```
This way I can preserve the same current structure I have.

**Comment by cytopia** [comment] 2019-01-09 21:13
@fkaminski this one might be interesting to you how to add official MySQL to the stack and make use of the desired variables: https://github.com/cytopia/devilbox/issues/466

**Comment by cytopia** [comment] 2019-02-08 19:49
@fkaminski official MySQL images will be integrated into the Devilbox shortly.

**Comment by cytopia** [comment] 2019-02-12 21:39
@fkaminski  could you try out the release branch: https://github.com/cytopia/devilbox/pull/416 Please pay special attention to the instructions in the PR description.

**Comment by cytopia** [comment] 2019-03-02 13:47
@fkaminski please let me now if this works out for you now with the above mentioned branch.

**Comment by fkaminski** [comment] 2019-03-05 09:09
Hi, with this branch a database will be generated with the settings mentioned above ( tested with mysql 5.7 ). So this works now as expected. Thank you.

I've set the Variable within the docker-compose-override.yml or within an own my-project1.yml file - see:
https://docs.docker.com/compose/extends/

However this only works once, or rather as long as no db Volume is present. 
To use multiple databases with an existing volume, they must be created manually afterwards - I think ...

**Comment by cytopia** [comment] 2019-03-05 09:34
That's good news. And yes I can confirm that this only works for a single database. It's a limitation of the official MySQL images, which I can't do anything about it.

So I will close this issue then.

**Closed by cytopia** 2019-03-05 09:34 UTC
Labels: feature, mysql
