### ISSUE TITLE
Deprecation on localhost/mail.php due to php.net/function.hexdec on PHP 7.4

### ISSUE THREAD

**Issue by masiorama** [cytopia/devilbox#798] opened 2021-04-12 11:13 UTC
### ISSUE TYPE

 - Bug Report

I switched to PHP 7.4 the ambient for some of my projects, and visiting devilbox/mail dashboad I notice a lot of warning like this:

```
Deprecated: Invalid characters passed for attempted conversion, these have been ignored in /var/www/default/include/vendor/Mail/mimeDecode.php on line 838
```

Checking the [php function](https://www.php.net/function.hexdec) it is stated that 

`hexdec() will ignore any non-hexadecimal characters it encounters. As of PHP 7.4.0 supplying any invalid characters is deprecated.`

Right now I have not time to investigate a bit more.
Will write down more infos as soon as possible.
Cheers!

**Comment by tiktaz** [comment] 2021-04-16 17:48
I'm facing same problem. Is it possible to add this correction around line 838 of `/var/www/default/include/vendor/Mail/mimeDecode.php` ?
```
if (ctype_xdigit($matches[0])) {
    return chr(hexdec($matches[0));
}
 ```

**Comment by llaville** [comment] 2021-04-17 08:45
Perharps a better alternative will be to replace outdated [PEAR Mail_mimeDecode](https://pear.php.net/package/Mail_mimeDecode) package, by a new alternative solution.

See https://stackoverflow.com/questions/4721410/best-way-to-handle-email-parsing-decoding-in-php

I suggest [eXorus answer](https://stackoverflow.com/a/24351629) with his solution https://github.com/php-mime-mail-parser/php-mime-mail-parser

**Comment by cytopia** [comment] 2022-01-30 11:27
@masiorama @tiktaz can you guys let me know how to reproduce it. I'm unable to get this error with PHP 7.4

**Comment by masiorama** [comment] 2022-01-31 12:36
Hi @cytopia neither I was able to reproduce the error.  Since then (when I opened the issue) I migrated my dev env to WSL2, installing Devilbox inside Ubuntu (on WSL2), and I have the previous env no more. What I can say is that building up the same stack I see no error in the mail section of Devilbox dashboard.

**Comment by cytopia** [comment] 2022-01-31 12:42
Alright, I'll give it a few more days to wait for @tiktaz and check if he's still facing this issue and if not I'm gonna close this one.

**Comment by lesteak** [comment] 2022-01-31 13:01
I've been facing this issue for some time with PHP7.4 and still am after updating to Devilbox 1.10.1 today. Thanks

**Comment by cytopia** [comment] 2022-01-31 13:06
> I've been experiencing this issue for some time with PHP7.4 and still am after updating to Devilbox 1.10.1 today. Thanks

Can you provide instructions on how one could reproduce this issue.

**Comment by tiktaz** [comment] 2022-02-09 15:49
Sorry I'm quit my last job and I'm not using Devilbox for the new one.
The way to get the bug was to sent a email containing some HTML tags and try to read them from localhost/mail.php.

**Comment by cytopia** [comment] 2022-04-08 10:17
> Perharps a better alternative will be to replace outdated [PEAR Mail_mimeDecode](https://pear.php.net/package/Mail_mimeDecode) package, by a new alternative solution.
> 
> See https://stackoverflow.com/questions/4721410/best-way-to-handle-email-parsing-decoding-in-php
> 
> I suggest [eXorus answer](https://stackoverflow.com/a/24351629) with his solution https://github.com/php-mime-mail-parser/php-mime-mail-parser

@llaville I had a look, unfortunately it's not gonna do it, as I do need support starting from PHP 5.3 onwards.

**Comment by cytopia** [comment] 2022-04-08 10:19
I am going to close this issue due to not being able to reproduce it (might have gone away with recent updates).

What I tried:

* Html emails
* Unicode characters
* Really large emails
* PHP 7.4 -> PHP 8.1

I've never encountered the deprecation warning.

If you encounter this again, please let me know exactly how it was triggered

**Comment by massiws** [comment] 2022-12-29 11:51
This error came up again after last update v-3.0.0 (both beta-0.1 and beta-0.2).
Tested with the same results on:

- Laravel project 
- sending Password Reset link (Laravel default notification)
- both PHP 8.0 and PHP 8.1
- HTML email 
- short text including characters `è`, and `é` (decimal 232, 233)

![mail](https://user-images.githubusercontent.com/6533289/209946936-75d17978-0f67-4d2e-bd14-ee6d82fd402b.png)

**Comment by cytopia** [comment] 2022-12-29 11:54
@massiws can you reproduce this behaviour with the "Send test Email" feature in the intranet?

**Comment by masiorama** [comment] 2022-12-29 14:54
It showed up again to me too.
This morning I upgraded from 2.2.0 to 2.4.0, and on PHP 8.0 it shows the same deprecation errors @massiws pasted right above.

**Comment by cytopia** [comment] 2022-12-29 17:00
I would require a command or a php snippet with which I can produce an email that triggers this error.

**Comment by masiorama** [comment] 2022-12-29 17:52
I am not sure what you are suggesting @cytopia. I am using no snippet at all, it is enough to visit devilbox "catch all emails" page to see all those deprecations. It is not related to any custom php project/script from my side.
I guess @massiws could be on the same page.

**Comment by cytopia** [comment] 2022-12-29 17:55
@masiorama what I am suggesting is any means of creating such an email. Whenever I create emails with UTF-8 chars they all display nicely on the vhost page. I don't see the errors, thus I can't really troubleshoot it. So all I need is the piece of code with which you send the email. Does this make sense now?

**Comment by masiorama** [comment] 2022-12-29 17:57
So you mean the deprecation is triggered by any email already trapped by devilbox? If so tomorrow I will check if the multiple messages are gone if I remove all emails, and I will dig a bit deeper and keep you posted, thanks.

**Comment by cytopia** [comment] 2022-12-29 18:00
> So you mean the deprecation is triggered by any email already trapped by devilbox? If so tomorrow I will check if the multiple messages are gone if I remove all emails, and I will dig a bit deeper and keep you posted, thanks.

Yes, it is seemlingly the "view/show emails" page. Also @massiws mentioned that those mails were send by other means and the error is shown on that page.

**Comment by massiws** [comment] 2022-12-29 23:02
> @massiws can you reproduce this behaviour with the "Send test Email" feature in the intranet?

@cytopia , using the "Send test Email" I can't reproduce the error: let me know if I can investigate more deeply

**Comment by masiorama** [comment] 2022-12-30 07:57
@cytopia indeed removing previous trapped emails the deprecations are gone and, as @massiws said, using "send test email" does not trigger them.

In my case the trapped emails were not customized "password recovery" email sent by laravel instance configured like this:

```
MAIL_MAILER=smtp
MAIL_HOST=localhost
MAIL_PORT=25
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
```

**Comment by cytopia** [comment] 2022-12-30 12:59
I don't have a laravel setup (at least not one with a registration page). Can you share the mbox file from inside the container at `/var/mail/devilbox` (If it doesn't contain any sensitive information)

**Comment by cytopia** [comment] 2023-01-02 11:29
I was able to reproduce it with [PHPMailer](https://github.com/PHPMailer/PHPMailer). I've implemented the fix as suggested by @tiktaz in this PR https://github.com/cytopia/devilbox/pull/944

This fixes it (at least for my tests)

**Comment by massiws** [comment] 2023-01-02 13:09
> I don't have a laravel setup (at least not one with a registration page). Can you share the mbox file from inside the container at `/var/mail/devilbox` (If it doesn't contain any sensitive information)

Below the `/var/mail/devilbox` content (only plain text):
![mail](https://user-images.githubusercontent.com/6533289/210235659-2b118f02-fa77-41a2-8b5e-68caaf98c875.png)


I can confirm that last beta-0.3 release fixes the issue.

**Closed** 2023-01-03 00:32 UTC
Labels: bug
