### ISSUE TITLE
Can't access Devilbox UI under localhost with Error 404

### ISSUE THREAD

**Issue by TheClonker** [cytopia/devilbox#242] opened 2018-05-03 12:09 UTC
Hi i can't access the Devilbox UI with a fresh copy from Devilbox. 

It worked a week or so ago and when i tried it today i would just get an error 404.
I deleted the devilbox directory and all Docker Images but it still doesn't work :/

I am using php-7.2, nginx-stable & mariadb-10.2 but i also tried it with apache-2.4 didnt make a difference. 

LOCAL_LISTEN_ADDR is empty and DEVILBOX_UI_DISABLE is 0 so it should be enabled.

By the way in the Issue Template and the [env-example](https://github.com/cytopia/devilbox/blob/master/env-example#L445) it reads HOST_PATH_TO_MYSQL_DATADIR when the actual Variable is named HOST_PATH_MYSQL_DATADIR without the "\_TO\_"!

Its also worth noting that the data folder is empty so no mysql data folder is generated but docker has drive access and also as you can propally guess the "/var/www/default/htdocs404" folder doesn't exist in the httpd Container.

I'm a little stumped and don't know where else to look or what to check for since i just started working with Docker. 

Anyway here are the Logs:

**docker-compose up httpd php mysql**
```
Creating devilbox_bind_1 ... done
Creating devilbox_php_1  ... done
Creating devilbox_httpd_1 ... done
Creating devilbox_mysql_1 ... done
Attaching to devilbox_php_1, devilbox_httpd_1, devilbox_mysql_1
php_1    | [INFO] Debug level: 1
php_1    | [INFO] Changing user 'devilbox' uid to: 1000
php_1    | usermod: no changes
php_1    | [INFO] Changing group 'devilbox' gid to: 1000
php_1    | [INFO] Setting container timezone to: Europe/Berlin
php_1    | [INFO] Setting PHP: timezone=Europe/Berlin
php_1    | [INFO] Docker date set to: Thu May  3 13:50:10 CEST 2018
php_1    | [INFO] $DOCKER_LOGS set to 1. Logging to docker logs (stdout and stderr).
php_1    | [INFO] $ENABLE_MAIL set to 1. Enabling postfix catch-all
httpd_1  | [INFO] $DOCKER_LOGS enabled. Redirecting errors and access to Docker log (stderr and stdout).
httpd_1  | [INFO] Setting docker timezone to: Europe/Berlin
httpd_1  | [INFO] Docker date set to: Thu May  3 13:50:11 CEST 2018
httpd_1  | [INFO] Changing user 'nginx' uid to: 1000
httpd_1  | [INFO] Changing group 'nginx' gid to: 1000
httpd_1  | [INFO] $MAIN_VHOST_DISABLE set to 0. Not disabling the default vhost.
httpd_1  | [INFO] $MAIN_VHOST_DOCROOT not specified. Keeping default: htdocs
httpd_1  | [INFO] $MAIN_VHOST_TPL not specified. Keeping default: cfg
httpd_1  | [INFO] $MAIN_VHOST_STATUS_ENABLE set to 1. Enabling httpd status.
httpd_1  | [INFO] Setting httpd status page to: '/devilbox-httpd-status'
httpd_1  | [INFO] $MASS_VHOST_ENABLE set to 1. Enabling mass vhosts.
httpd_1  | [INFO] $MASS_VHOST_TLD set to: .local
httpd_1  | [INFO] $MASS_VHOST_DOCROOT is set to: htdocs
httpd_1  | [INFO] $MASS_VHOST_TPL is set to: cfg
httpd_1  | [INFO] $PHP_FPM_ENABLE set to 1. Enabling PHP-FPM.
httpd_1  | [INFO] $PHP_FPM_SERVER_ADDR is set to: php
httpd_1  | [INFO] $PHP_FPM_SERVER_PORT is set to: 9000
httpd_1  | vhostgen: [2018-05-03 13:50:11] Adding: localhost
httpd_1  | 2018-05-03 13:50:12,189 CRIT Set uid to user 0
httpd_1  | 2018-05-03 13:50:12,197 INFO supervisord started with pid 1
mysql_1  | [INFO] Setting docker timezone to: Europe/Berlin
mysql_1  | root $ rm /etc/localtime
mysql_1  | root $ ln -s /usr/share/zoneinfo/Europe/Berlin /etc/localtime
mysql_1  | [INFO] Docker date set to: Thu May  3 13:50:12 CEST 2018
mysql_1  | [INFO] Setting MySQL: [mysqld] general-log=1
mysql_1  | root $ touch /etc/my.cnf.d/logging.cnf
mysql_1  | root $ echo '[mysqld]' >> /etc/my.cnf.d/logging.cnf
mysql_1  | root $ echo 'general-log = 1' >> /etc/my.cnf.d/logging.cnf
mysql_1  | [INFO] Setting MySQL: [client] socket=/tmp/mysql/mysqld.sock
mysql_1  | root $ touch /etc/my.cnf.d/socket.cnf
mysql_1  | root $ echo '[client]' >> /etc/my.cnf.d/socket.cnf
mysql_1  | root $ echo 'socket = /tmp/mysql/mysqld.sock' >> /etc/my.cnf.d/socket.cnf
mysql_1  | [INFO] Setting MySQL: [mysql] socket=/tmp/mysql/mysqld.sock
mysql_1  | root $ echo '[mysql]' >> /etc/my.cnf.d/socket.cnf
mysql_1  | root $ echo 'socket = /tmp/mysql/mysqld.sock' >> /etc/my.cnf.d/socket.cnf
mysql_1  | [INFO] Setting MySQL: [mysqld] socket=/tmp/mysql/mysqld.sock
mysql_1  | root $ echo '[mysqld]' >> /etc/my.cnf.d/socket.cnf
mysql_1  | root $ echo 'socket = /tmp/mysql/mysqld.sock' >> /etc/my.cnf.d/socket.cnf
mysql_1  | root $ mkdir -p /tmp/mysql
mysql_1  | root $ chown mysql:mysql /tmp/mysql
mysql_1  | root $ chmod 0777 /tmp/mysql
php_1    | [INFO] Forwarding mysql:3306 to 127.0.0.1:3306 inside this docker.
php_1    | [INFO] Forwarding pgsql:5432 to 127.0.0.1:5432 inside this docker.
php_1    | [INFO] Forwarding redis:6379 to 127.0.0.1:6379 inside this docker.
php_1    | [INFO] Forwarding memcd:11211 to 127.0.0.1:11211 inside this docker.
php_1    | [INFO] Forwarding mongo:27017 to 127.0.0.1:27017 inside this docker.
php_1    | [INFO] Enabling 'socat-3306-mysql-3306' to be started by supervisord
php_1    | [INFO] Enabling 'socat-5432-pgsql-5432' to be started by supervisord
php_1    | [INFO] Enabling 'socat-6379-redis-6379' to be started by supervisord
php_1    | [INFO] Enabling 'socat-11211-memcd-11211' to be started by supervisord
php_1    | [INFO] Enabling 'socat-27017-mongo-27017' to be started by supervisord
php_1    | [INFO] Enabling 'rsyslogd' to be started by supervisord
php_1    | [INFO] Enabling 'postfix' to be started by supervisord
php_1    | [INFO] Enabling 'php-fpm' to be started by supervisord
mysql_1  | root $ touch /var/log/mysql/query.log
mysql_1  | root $ touch /var/log/mysql/slow.log
mysql_1  | root $ touch /var/log/mysql/error.log
mysql_1  | root $ chown -R mysql:mysql /var/lib/mysql/
mysql_1  | root $ chown -R mysql:mysql /var/lib/mysql
mysql_1  | root $ chown -R mysql:mysql /var/log/mysql
mysql_1  | root $ chown -R mysql:mysql /var/run/mysqld
mysql_1  | root $ chown -R mysql:mysql /var/sock/mysqld
mysql_1  | root $ chmod 0775 /var/lib/mysql/
mysql_1  | root $ chmod 0775 /var/lib/mysql
mysql_1  | root $ chmod 0775 /var/log/mysql
mysql_1  | root $ chmod 0775 /var/run/mysqld
mysql_1  | root $ chmod 0775 /var/sock/mysqld
mysql_1  | root $ find /var/log/mysql/ -type f -exec chmod 0664 {} \;
mysql_1  | [INFO] No existing MySQL data directory found. Setting up MySQL for the first time.
mysql_1  | root $ mysql_install_db --datadir=/var/lib/mysql/ --user=mysql
mysql_1  | Installing MariaDB/MySQL system tables in '/var/lib/mysql/' ...
httpd_1  | 2018-05-03 13:50:13,199 INFO spawned: 'nginx' with pid 119
httpd_1  | 2018-05-03 13:50:13,201 INFO spawned: 'watcherd' with pid 120
httpd_1  | watcherd: [2018-05-03 13:50:13] Starting daemon.
httpd_1  | watcherd: [2018-05-03 13:50:13] Using bash loop to watch for changes.
php_1    | [INFO] $MYSQL_BACKUP_USER set for mysqldump-secure. Changing to 'root'
php_1    | [INFO] $MYSQL_BACKUP_PASS set for mysqldump-secure. Changing to '******'
php_1    | [INFO] $MYSQL_BACKUP_HOST set for mysqldump-secure. Changing to 'mysql'
php_1    | [INFO] Starting supervisord
php_1    | 2018-05-03 13:50:13,639 CRIT Set uid to user 0
php_1    | 2018-05-03 13:50:13,639 INFO Included extra file "/etc/supervisor/conf.d/php-fpm.conf" during parsing
php_1    | 2018-05-03 13:50:13,639 INFO Included extra file "/etc/supervisor/conf.d/postfix.conf" during parsing
php_1    | 2018-05-03 13:50:13,639 INFO Included extra file "/etc/supervisor/conf.d/rsyslogd.conf" during parsing
php_1    | 2018-05-03 13:50:13,639 INFO Included extra file "/etc/supervisor/conf.d/socat-11211-memcd-11211.conf" during parsing
php_1    | 2018-05-03 13:50:13,639 INFO Included extra file "/etc/supervisor/conf.d/socat-27017-mongo-27017.conf" during parsing
php_1    | 2018-05-03 13:50:13,639 INFO Included extra file "/etc/supervisor/conf.d/socat-3306-mysql-3306.conf" during parsing
php_1    | 2018-05-03 13:50:13,639 INFO Included extra file "/etc/supervisor/conf.d/socat-5432-pgsql-5432.conf" during parsing
php_1    | 2018-05-03 13:50:13,639 INFO Included extra file "/etc/supervisor/conf.d/socat-6379-redis-6379.conf" during parsing
php_1    | 2018-05-03 13:50:13,645 INFO supervisord started with pid 1
httpd_1  | 2018-05-03 13:50:14,259 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
httpd_1  | 2018-05-03 13:50:14,259 INFO success: watcherd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
php_1    | 2018-05-03 13:50:14,649 INFO spawned: 'rsyslogd' with pid 341
php_1    | 2018-05-03 13:50:14,649 INFO spawned: 'socat-3306-mysql-3306' with pid 342
php_1    | 2018-05-03 13:50:14,650 INFO spawned: 'socat-6379-redis-6379' with pid 343
php_1    | 2018-05-03 13:50:14,651 INFO spawned: 'postfix' with pid 344
php_1    | 2018-05-03 13:50:14,652 INFO spawned: 'socat-27017-mongo-27017' with pid 345
php_1    | 2018-05-03 13:50:14,653 INFO spawned: 'php-fpm' with pid 346
php_1    | 2018-05-03 13:50:14,660 INFO spawned: 'socat-11211-memcd-11211' with pid 347
php_1    | 2018-05-03 13:50:14,661 INFO spawned: 'socat-5432-pgsql-5432' with pid 348
php_1    | rsyslogd: imklog: cannot open kernel log (/proc/kmsg): Operation not permitted.
php_1    | rsyslogd: activation of module imklog failed [v8.24.0 try http://www.rsyslog.com/e/2145 ]
php_1    | [03-May-2018 13:50:14] NOTICE: fpm is running, pid 346
php_1    | [03-May-2018 13:50:14] NOTICE: ready to handle connections
mysql_1  | OK
mysql_1  |
mysql_1  | To start mysqld at boot time you have to copy
mysql_1  | support-files/mysql.server to the right place for your system
mysql_1  |
mysql_1  | PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
mysql_1  | To do so, start the server, then issue the following commands:
mysql_1  |
mysql_1  | '/usr/bin/mysqladmin' -u root password 'new-password'
mysql_1  | '/usr/bin/mysqladmin' -u root -h 172.16.238.12 password 'new-password'
mysql_1  |
mysql_1  | Alternatively you can run:
mysql_1  | '/usr/bin/mysql_secure_installation'
mysql_1  |
mysql_1  | which will also give you the option of removing the test
mysql_1  | databases and anonymous user created by default.  This is
mysql_1  | strongly recommended for production servers.
mysql_1  |
mysql_1  | See the MariaDB Knowledgebase at http://mariadb.com/kb or the
mysql_1  | MySQL manual for more instructions.
mysql_1  |
mysql_1  | You can start the MariaDB daemon with:
mysql_1  | cd '/usr' ; /usr/bin/mysqld_safe --datadir='/var/lib/mysql/'
mysql_1  |
mysql_1  | You can test the MariaDB daemon with mysql-test-run.pl
mysql_1  | cd '/usr/mysql-test' ; perl mysql-test-run.pl
mysql_1  |
mysql_1  | Please report any problems at http://mariadb.org/jira
mysql_1  |
mysql_1  | The latest information about MariaDB is available at http://mariadb.org/.
mysql_1  | You can find additional information about the MySQL part at:
mysql_1  | http://dev.mysql.com
mysql_1  | Consider joining MariaDB's strong and vibrant community:
mysql_1  | https://mariadb.org/get-involved/
mysql_1  |
mysql_1  | root $ mysqld --skip-networking &
mysql_1  | [INFO] Initializing ...
mysql_1  | 2018-05-03 13:50:15 140321485830272 [Note] mysqld (mysqld 10.2.13-MariaDB-log) starting as process 166 ...
php_1    | 2018-05-03 13:50:15,947 INFO success: rsyslogd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
php_1    | 2018-05-03 13:50:15,948 INFO success: socat-3306-mysql-3306 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
php_1    | 2018-05-03 13:50:15,948 INFO success: socat-6379-redis-6379 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
php_1    | 2018-05-03 13:50:15,948 INFO success: postfix entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
php_1    | 2018-05-03 13:50:15,948 INFO success: socat-27017-mongo-27017 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
php_1    | 2018-05-03 13:50:15,949 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
php_1    | 2018-05-03 13:50:15,950 INFO success: socat-11211-memcd-11211 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
php_1    | 2018-05-03 13:50:15,950 INFO success: socat-5432-pgsql-5432 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
mysql_1  | [INFO] Setting up root user permissions.
mysql_1  | [INFO] Shutting down MySQL.
mysql_1  | root $ kill -s TERM 166
mysql_1  | [INFO] MySQL successfully installed.
mysql_1  | [INFO] Starting mysqld  Ver 10.2.13-MariaDB-log for Linux on x86_64 (MariaDB Server)
mysql_1  | 2018-05-03 13:50:17 140452300167296 [Note] mysqld (mysqld 10.2.13-MariaDB-log) starting as process 1 ...
httpd_1  | 2018/05/03 13:50:22 [error] 138#138: *1 open() "/var/www/default/htdocs404" failed (2: No such file or directory), client: 172.16.238.1, server: _, request: "GET / HTTP/1.1", host: "localhost"
httpd_1  | 172.16.238.1 - - [03/May/2018:13:50:22 +0200] "GET / HTTP/1.1" 404 571 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36"
httpd_1  | 2018/05/03 13:50:22 [error] 138#138: *1 open() "/var/www/default/htdocs404" failed (2: No such file or directory), client: 172.16.238.1, server: _, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/"
httpd_1  | 172.16.238.1 - - [03/May/2018:13:50:22 +0200] "GET /favicon.ico HTTP/1.1" 404 571 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36"
Gracefully stopping... (press Ctrl+C again to force)
Stopping devilbox_mysql_1 ... done
Stopping devilbox_httpd_1 ... done
Stopping devilbox_php_1   ... done
```

**Windows 10 x64**

**docker version**
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: true

**docker-compose version**
docker-compose version 1.21.1, build 7641a569
docker-py version: 3.2.1
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017

**Comment by cytopia** [comment] 2018-05-05 11:26
@TheClonker `docker-compose logs` seems good so far. Can you attach the php and httpd logs (for your version) from the `./logs/` directory.

**Comment by TheClonker** [comment] 2018-05-05 13:10
@cytopia Hey, thanks for replying, are you talking about the `devilbox/log/` Folder or the `/var/log/` Folder in the php and httpd Containers ?

The `devilbox/log/` Folder is empty since i have DOCKER_LOGS=1 so these are all the logs i get. 

I did some digging in the httpd container and in the `/etc/httpd/conf.d/localhost.conf` nginx config file the root dir is `/var/www/default/htdocs/` but that doesn't exist. 
What is the `/var/www/default/` Directory in the httpd Container supposed to look like ? 
Shouldn't the be a symbolic link to (or a copy of) `devilbox\.devilbox\www` in there ? 
Where are you linking these to directories, because i think thats where to root of my error is.

**Comment by cytopia** [comment] 2018-05-05 13:40
> @cytopia Hey, thanks for replying, are you talking about the devilbox/log/ Folder or the /var/log/ Folder in the php and httpd Containers ?

That's more or less the same, anyway as you are using DOCKER_LOGS, it doesn't matter.

> What is the /var/www/default/ Directory in the httpd Container supposed to look like ?

It should actually mount what you will find in the Devilbox git directory under `./devilbox/www/` into `/var/www/default/` (both in httpd and php container).

Does the `/var/www/default/htdocs` exist in the PHP container (as I understood it does not exist in your httpd container)?

**Comment by cytopia** [comment] 2018-05-05 13:40
Also, just to be sure do a 
```
docker-compose pull php
docker-compose pull httpd
```

**Comment by cytopia** [comment] 2018-05-05 22:01
Sorry, got auto-closed by a PR

**Comment by TheClonker** [comment] 2018-05-05 22:14
@cytopia No there is no /var/www/default/htdocs in the PHP container and the containers are all up to date

**Comment by cytopia** [comment] 2018-05-06 08:48
It will make sense if I add all the required steps for windows to the documentation, so from what I gathered it was:

* docker network must be a `home network`
* grant rights to the drive? (do you happen to have any screenshot of that)

**Comment by TheClonker** [comment] 2018-05-06 15:43
Hey exactly, the Docker Network Adapter had to be a "home network" for my firewall to not block the attempts to access my drive. Could be diffrent for other Firewalls though!

What helped me was this https://docs.docker.com/docker-for-windows/#shared-drives
There are some screenshots and tipps on the page how to get it working. 
Maybe just link this page in the Documentation or the FAQ ?

**Comment by dtrilsbeek** [comment] 2018-07-04 17:45
Hi,

I've recently tried out this image. On the first day(right after installation) it worked fine and I was impressed.

However the second day(today) I tried running the devilbox and I get a 404 error on localhost. The thing why I'm commenting is because I have the most standard docker setup there is. (fresh install of windows, fresh install of docker. So I don't think this should be the standard installation manual ;)

Other images on docker with docker compose are running fine. Also with shared drives and volumes.

Let me know what you think

**Comment by cytopia** [comment] 2018-07-05 07:16
Probably related to: https://github.com/cytopia/devilbox/issues/288

**Comment by cytopia** [comment] 2018-07-05 07:21
In order to reproduce, lets gather some basic information from everybody having this problem.

1. Host OS
2. Docker native or Docker Toolbox
3. Docker and Docker Compose version
4. Use default settings (except UID/GID)

Try the following if it helps:
```
docker-compose stop
docker-compose kill
docker-compose rm -f
```
And only start the base set of containers
```
docker-compose up httpd php bind
```

Also please provide the following:
```
docker ps
```
As well as the information from php and httpd server:
```
docker inspect <ID_OF_HTTPD_CONTAINER>
docker inspect <ID_OF_PHP_CONTAINER>
```

**Comment by cytopia** [comment] 2018-07-06 14:58
@dtrilsbeek How long was the time gap between first and second try?

There was a change in `env-example` that reverted the behaviour of intranet enabled/disabled.
You should probably diff your current `.env` file against the current `env-example` file to see any changes that occured

**Comment by dtrilsbeek** [comment] 2018-07-12 11:01
I've noticed that the httpd, php and bind container are apparently run on start. 
Then when i try docker-compose up, 'll get the 404 error. 

If I do a docker-compose stop before running them again, everything works fine. (see image)
![image](https://user-images.githubusercontent.com/7400410/42629410-82fa3050-85d3-11e8-84c6-6362e2c0467f.png)

Note that I didn't start the httpd php and bind manually and I did do a docker-compose stop when exiting.

**Comment by cytopia** [comment] 2018-07-12 16:38
@dtrilsbeek not sure If I can follow. What are the exact steps to reproduce the `404 behaviour`?

**Comment by dtrilsbeek** [comment] 2018-07-12 20:23
@cytopia Okay, i'll try to be more specific.

When starting up my computer, docker starts up with windows. 
If i check what cointainers are running with docker ps, these three containers are already running! (they shouldn't)
![image](https://user-images.githubusercontent.com/7400410/42657077-802b7264-8621-11e8-9b35-d61723bd61e9.png)

If I now try to docker-compose up -d from within devilbox folder. it tries to recreate these cointainers and start the others.

if I now visit localhost I will get the 404 error.

In order to not get the 404 error I can just simply do a docker-compose stop every time I start docker

I hope it's more clear now :)

**Comment by dtrilsbeek** [comment] 2018-07-12 20:46
That's it, now only devilbox_bind is starting on startup. Should I disable that too? 

Thanks,

**Comment by cytopia** [comment] 2018-07-12 20:55
I would guess so. 

@TheClonker can you check if this also fixes your problem?

If will create an PR to make it permanent

**Comment by TheClonker** [comment] 2018-07-12 20:57
Hi, all my Problems had been fixed after "re-sharing" my Drives.

**Closed** 2018-07-17 06:47 UTC
Labels: bug, help wanted, host:windows

**Comment by BlueTeck** [comment] 2019-05-16 06:35
Setting the Docker Network Adapter Private helped me:

`Set-NetConnectionProfile -interfacealias "vEthernet (DockerNAT)" -NetworkCategory Private`

Credtits to: https://stackoverflow.com/a/52725920/4921098
