### ISSUE TITLE
Uglifyjs and Uglifycss

### ISSUE THREAD

**Issue by Alephel** [cytopia/devilbox#607] opened 2019-07-17 00:48 UTC
#### ISSUE TYPE

 - Feature request

#### SUMMARY

It will be great to have these tools for minifying and packaging assets for production deployment, node and rpm is bundled. I have tried installing but of course, the installation is lost anytime the machine is restarted

#### Goal

Package assets for deployment

**Comment by dimkasta** [comment] 2019-07-23 09:11
Until the feature is considered, you can create a bash script inside ~/devilbox/bash/ to install these whenever you spin a new container. 
I use this to config/initialize git, and run my composer/yarn/etc init scripts.

**Comment by dbd5** [comment] 2019-07-24 12:29
Thanks @dimkasta 

I have just done this and it works

HOWEVER -- and please correct me if I am missing something.

It will be very helpful to get back into the state that has been setup without doing new installations all the time. A similar example is tasks saves to cron. Do you think @cytopia will consider a way to save and restore state such that installations to the box and configurations like those saved for cron wouldn't need to be setup afresh?

What do you think?

**Comment by dimkasta** [comment] 2019-07-24 13:56
npm, composer etc packages (including their dependency management, versioning and configuration) are project specific, so their place is in the configuration files of your package managers in your project folder.

That's what makes the immutability of docker images work in the first place.

**Comment by dbd5** [comment] 2019-07-31 07:42
@dimkasta ,

We're not disputing the value of the immutability of docker images.
The context of my questions is that I shut down my development computer every evening when I'm done and restart it every morning when I resume work, I need a simple way to reload the environment without going through any new installation steps.

I have cron jobs that mirror what will be in production.
I use uglifyCss and uglifyJs to compress assets.

The bash scripts work and will serve till the feature is considered, thanks to your recommendation.
But the script is a work around. I am looking at the purpose of devilbox itself, it's built on docker to take advantage of the immutability you speak of but I suggest that it makes sense for one of its value add be restoring the configured development state on restart.

We can have docker immutability as well as a fixed development environment without reinstalls and reconfiguration on each restart

**Comment by dimkasta** [comment] 2019-08-01 15:04
You touch two very different points.

About the tools, even if Cytopia decides not to include them, there is a very easy way to make them persistent. It is to install them locally on your project directory, not globally. That way they are available to the container every time you boot it. You need to re-install them only if you clone your code on a new machine (assuming you do not include them in your source management). That's where tools like NPM, composer, phive etc come very handy.

Cron settings on the other hand is something very different. You are still thinking of state persistence in terms of virtualization where we would save the machine state and restart it next time you needed the machine. The disadvantage in this approach is that state is temporary and local to your machine. If you wanted to start the environment on your brand new laptop or give it to a colleague, you would have to manually re-enter the commands or copy the state itself along with the rest of the project.

Initialization scripts on the other hand is the way to properly do this. It's not a work around and has many advantages. Mostly because it makes environment initialization part of your code and includes it in your source management tool where you can easily and/or automatically reapply or fine tune it. It documents the process and makes it easily reproducible by your or anyone else that might have to set a new machine, for development or for production. Especially in the not-so-near future when you would have forgotten the structure of the project.

A different approach would be to extend devilbox to create your own images that already include the initialization. But it's hardly worth the effort. You would have to manage docker files and images on top of the initialization scripts.

**Comment by cytopia** [comment] 2019-11-17 22:19
@Alephel @dbd5 You can install whatever tools inside each of the Docker container. If you simply stop them `docker-compose stop` and do not remove them `docker-compose rm -f`, then you state is preserved and you can just start it up again and still have all the installed tools available.

**Closed** 2019-11-17 22:19 UTC
Labels: feature
