### ISSUE TITLE
Devilbox on VPS : No Host DNS record found

### ISSUE THREAD

**Issue by Myster-Gh0s7** [cytopia/devilbox#220] opened 2018-04-13 06:33 UTC
I'm a big fan of Devil box but this freaking error causing me a big headache.

I've Ubuntu VPS and I've installed docker-compose on it but I've implemented this at my local Windows machine and everything works fine on it using AutoDNS but I've no idea on how to implement on VPS or DNS. Can you guys help me to fix to create a virtual host with or without domain

Modified TLD in .env to ".com" instead of ".loc" and port 1053 to 53 and no services are running on the host which are using port 80, 3306 or 53

I've done everything in AutoDNS configuration guide but still, Why i'm getting this error.

No Host DNS record found. Add the following to /etc/hosts:
127.0.0.1 mydomain.com

Or is it Devil box is not capable to run on VPS?

**Comment by cytopia** [comment] 2018-04-13 07:36
@Myster-Gh0s7 it should run anywhere, there are no limitations.

The new documentation for Auto-DNS is here: http://devilbox.readthedocs.io/en/documentation/configuration-global/auto-dns.html
Can you check if everything for Linux is done as described.

If you have an official `*.com` domain and its DNS record points to that server, you actually don't need Auto-DNS.

Can you tell me a bit more about your setup on the VPS. How many projects and if you do have a real DNS record or not.

You could actually also fully customize your vhost and do not rely on the `TLD_SUFFIX`. For that see here: http://devilbox.readthedocs.io/en/documentation/configuration-project/custom-vhost.html

**Comment by Myster-Gh0s7** [comment] 2018-04-13 08:14
@cytopia Thanks so much for the new guide, I'll look into that.

My VPS is Ubuntu 16.04 which is hosted on Digital Ocean and yeah I think every requirement is fulfilled to my knowledge. 

Yeah I do have original DNS record but previously SSL was installed on it so now it's redirecting to https so i don't know how to stop redirecting to it so, for now, I'm using just an Ip address for just to setup devil box and TLD suffix which is little confusing for me. I've read your last link about custom vhost template which is also very complex for me can you just guide me how can i setup multi projects using subdomain or whatever so i can make my project online. If you want I can provide the login details for my server.

**Comment by cytopia** [comment] 2018-04-13 09:45
> Yeah I do have original DNS record but previously SSL was installed on it so now it's redirecting to https so i don't know how to stop redirecting to it so, for now,

This is probably the browser cache (try incognito), or you might even had an HSTS header, so it will always redirect.

The problem will also be addressed soon, as the Devilbox gets https support shortly.

> If you want I can provide the login details for my server.

I'd rather not do that with people's own server. We should find a solution together to get this working.

**Comment by Myster-Gh0s7** [comment] 2018-04-13 09:58
> This is probably the browser cache (try incognito), or you might even had an HSTS header, so it will always redirect.

Yeah that helped man, Thanks

> The problem will also be addressed soon, as the Devil box gets https support shortly: #173 

That's awesome, Looking forward to it.

> I'd rather not do that with people's own server. We should find a solution together to get this working.

No, i completely understand that it just I already spent too much time (8 hours already) to fix this and instead of working on my project before coming here but I really appreciate that you're offering help at this time.  I'm up all to fix this once and for all.

**Comment by cytopia** [comment] 2018-05-05 11:39
@Myster-Gh0s7 try out the `https` branch https://github.com/cytopia/devilbox/pull/239 and let me know if that works. It now has full HTTPS support. (Instructions in PR)

**Comment by cytopia** [comment] 2018-05-05 15:43
Btw can you check if the DNS server is actually resolving? Try to ping any of your project domains from the Linux server

**Comment by cytopia** [comment] 2018-07-05 07:38
The fix has been merged a whole ago: https://github.com/cytopia/devilbox/pull/239

Does this problem still persist?

**Comment by cytopia** [comment] 2018-07-17 07:15
@Myster-Gh0s7 I will close this issue due to inactivity, feel free to append comments if the problem still persists and I will re-open.

**Closed by cytopia** 2018-07-17 07:15 UTC
Labels: DNS, host:linux, needs more info

**Comment by adriennn** [comment] 2018-09-14 20:34
on linux, the sites can be pinged no problem. Looks like a CORS problem perhaps?
![screenshot from 2018-09-14 23-32-05](https://user-images.githubusercontent.com/7082644/45573826-7a299f80-b876-11e8-9ddc-52791fd56bd9.png)

**Comment by cytopia** [comment] 2018-10-26 21:59
I tried very hard to get rid of the CORS issue in the past. FYI: You should not use `.local` as a TLD_SUFFIX: https://devilbox.readthedocs.io/en/latest/configuration-files/env-file.html#tld-suffix

Can you add some more details about your system (OS, env file, Docker version, etc) and steps to reproduce.

**Comment by kritostar** [comment] 2021-11-10 15:58
> on linux, the sites can be pinged no problem. Looks like a CORS problem perhaps? ![screenshot from 2018-09-14 23-32-05](https://user-images.githubusercontent.com/7082644/45573826-7a299f80-b876-11e8-9ddc-52791fd56bd9.png)

I am having the same problem with a site .loc
