### ISSUE TITLE
php project showing Bad Request on apache-2.4, apache-2.2, however it works on nginx 

### ISSUE THREAD

**Issue by alzen8work** [cytopia/devilbox#224] opened 2018-04-16 09:54 UTC
As I have few project running on bare-metal apache 2.4, I was wondering 
how to setup a dockerize version, here is the issue I face:

apache-2.4, apache-2.2 my project showing Bad Request

I have configured C:\Windows\System32\drivers\etc\hosts
![image](https://user-images.githubusercontent.com/20431509/38802400-ec93f84e-419e-11e8-856e-a6e3dc9d67dc.png)

Set apache2.4 to be httpd server
![image](https://user-images.githubusercontent.com/20431509/38802440-05b6aa4c-419f-11e8-9622-48c6975e9b51.png)
![image](https://user-images.githubusercontent.com/20431509/38802444-0907ec24-419f-11e8-93d5-b9cce0586863.png)
![image](https://user-images.githubusercontent.com/20431509/38802450-0bc0c8e6-419f-11e8-8214-0567570aa5a2.png)

Where as i setup in nginx for the same project, it works:
![image](https://user-images.githubusercontent.com/20431509/38802477-1ee5a266-419f-11e8-96f2-7598ad4497fd.png)
![image](https://user-images.githubusercontent.com/20431509/38802483-2187c95e-419f-11e8-84c1-30af1446563c.png)
<img width="521" alt="screenshot_5" src="https://user-images.githubusercontent.com/20431509/38804170-090abada-41a4-11e8-87d5-4f2bb456d94d.png">

Any Ideas what's the root cause?

Perhaps It would be great if there is any tips regarding setting up apache that i din't know?

**Comment by cytopia** [comment] 2018-04-16 11:15
That's strange. 

Let's make sure we are both on the same page and please provide some more details for me to work with.

1. Please provide Docker and Docker-Compose version
2. Are you using Docker for Windows or Docker Toolbox?
3. When having selected Apache in `.env`, could you pull latest image via `docker-compose pull httpd`
4. Please provide `docker-compose logs` output when Apache is enabled
5. Please provide Apache logs from `./logs/` directory

**Comment by alzen8work** [comment] 2018-04-16 14:46
1) Please provide Docker and Docker-Compose version
-Docker Version: 18.03.0-ce-win59 (16762)
-Docker Machine 0.14.0
-Docker compose 1.20.1
-Notary 0.6.0

2) Are you using Docker for Windows or Docker Toolbox?
-Windows 10 Pro 
- Docker for Windows (hyper-v)

3) When having selected Apache in .env, could you pull latest image via docker-compose pull httpd
![box2](https://user-images.githubusercontent.com/20431509/38815869-7718097e-41c7-11e8-8815-182598df63e1.png)

docker images
![box](https://user-images.githubusercontent.com/20431509/38815913-87ce2d5c-41c7-11e8-810e-ee2b8d697b30.png)

4) Please provide docker-compose logs output when Apache is enabled
[docker-compose logs .txt](https://github.com/cytopia/devilbox/files/1915791/docker-compose.logs.txt)

docker-compose up
[docker-compose up .txt](https://github.com/cytopia/devilbox/files/1915798/docker-compose.up.txt)

5) Please provide Apache logs from ./logs/ directory
./logs/apache-2.4/ files are all empty

**Comment by cytopia** [comment] 2018-04-16 14:54
Did you upgrade from a previous Devilbox version or start from scratch?

**Comment by alzen8work** [comment] 2018-04-16 15:06
well im git pulling from previous version

**Comment by cytopia** [comment] 2018-04-16 15:07
Can you please compare `env-example` with your current `.env` in case something is missing.

**Comment by alzen8work** [comment] 2018-04-16 15:09
PS:
I have also tested the same repo on server, the same issue persist:

server specs:
Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-693.17.1.el7.x86_64
      Architecture: x86-64
Docker

docker -v
Docker version 17.12.1-ce, build 7390fc6

docker-compose -v
docker-compose version 1.20.0-rc1, build 86428af

On the other hand,
Another set of local windows 10 pro PC with previous version of apache :
Docker 17.12.0-ce-win47 (15139)
Docker-compose 1.18.0

Which run on previous version of devilbox(php5.6.31, apache 2.4.27) repo is working fine 
![working fine3](https://user-images.githubusercontent.com/20431509/38817597-425b87b6-41cb-11e8-9bea-512e38ce3409.png)
![working fine2](https://user-images.githubusercontent.com/20431509/38817598-42ace85e-41cb-11e8-81e5-069925e26854.png)
![working fine](https://user-images.githubusercontent.com/20431509/38817601-42e808c6-41cb-11e8-98d7-018ee4f69f30.png)

**Comment by cytopia** [comment] 2018-04-16 15:20
Does it work now?

**Comment by alzen8work** [comment] 2018-04-16 15:20
Can you please compare env-example with your current .env in case something is missing.

Oops accidentally close the issue

**Comment by alzen8work** [comment] 2018-04-16 15:21
Oops, accidentally close the issue.
Nope. still the same

RE: an you please compare env-example with your current .env in case something is missing.
![diff4](https://user-images.githubusercontent.com/20431509/38818222-d6773908-41cc-11e8-842c-5dcc0433d3c0.png)
![diff3](https://user-images.githubusercontent.com/20431509/38818224-d6ad6cc6-41cc-11e8-88aa-2013d84152d1.png)
![diff2](https://user-images.githubusercontent.com/20431509/38818225-d6e98576-41cc-11e8-9365-4ac118cec81e.png)
![diff](https://user-images.githubusercontent.com/20431509/38818226-d7236b1a-41cc-11e8-90b2-3413d949ba44.png)

**Comment by alzen8work** [comment] 2018-04-16 15:34
@cytopia well in summary seems like:
 
windows 10 pro machine which has the updated docker+ updated devilbox(php5.6.35, apache 2.4.29)
is not working

Centos 7 which has the older docker + updated devilbox(php5.6.35, apache 2.4.29)
is not working

where as,
another windows 10 pro that has older docker + older devilbox(php5.6.31, apache 2.4.27) repo 
is working fine

hmmm....

**Comment by cytopia** [comment] 2018-04-16 15:50
This is very strange as it even works inside Travis ci.
One more thing you could try to have a fresh start is

#### Remove old stuff
```bash
host> docker-compose stop
host> docker-compose kill
host> docker-compose rm -f
```
#### Remove current network
```bash
host> docker network ls | grep devilbox
1168ebab4133        devilbox_app_net            bridge              local

host> docker network rm devilbox_app_net
```

**Comment by alzen8work** [comment] 2018-04-16 15:57
sorry dont get it, One more thing you could try to have a fresh start is?

**Comment by alzen8work** [comment] 2018-04-16 15:58
![screenshot_4](https://user-images.githubusercontent.com/20431509/38821025-023dc354-41d2-11e8-8c5c-2d08a311143a.png)

**Comment by cytopia** [comment] 2018-04-16 16:01
Hmm strange that there is no `devilbox_app_net` network. Could you just issue `docker network ls` and show the output here.

**Comment by alzen8work** [comment] 2018-04-16 16:03
well @cytopia , i think it is because i "docker-compose down" before i execute ur command

**Comment by alzen8work** [comment] 2018-04-16 16:05
docker network ls
![screenshot_5](https://user-images.githubusercontent.com/20431509/38821396-f9b73fb6-41d2-11e8-9e6b-afcfbcf65a3f.png)

**Comment by alzen8work** [comment] 2018-04-16 16:08
well if docker images:


devilbox/nginx-stable   0.12                da8e151ed02a        6 months ago        148MB
devilbox/php-fpm        5.6-work            8001cc57e6ab        7 hours ago         1.43GB
devilbox/nginx-stable   0.13                91add6c5b204        4 weeks ago         169MB
devilbox/apache-2.4     0.13                eb973214ec30        4 weeks ago         241MB
cytopia/mariadb-10.1    latest              cadf2d610e84        7 weeks ago         1.22GB
cytopia/mysql-5.7       latest              ac5e1664fe95        7 weeks ago         1.37GB
cytopia/php-fpm-7.1     latest              927ad858fb6a        7 months ago        1.1GB
cytopia/php-fpm-7.2     latest              583d55de7ac1        7 months ago        1.08GB
cytopia/bind            0.11                3a06fe34e4ff        2 months ago        198MB
cytopia/bind            latest              3bff038174ca        2 months ago        199MB

**Comment by cytopia** [comment] 2018-04-21 11:13
I am afraid not yet. I will come back to this issue shortly after having tried it on CentOS 7.

**Comment by codeteo** [comment] 2018-05-29 19:38
I think this is because of the underscore @alzen8work used for the host name.
Check also this StackOverflow [answer](https://stackoverflow.com/a/2183140/423980) .

I had a quite similar issue and solve it by creating another host named `second-project` (please note the dash I used instead of underscore).

Hope this helps!

**Comment by cytopia** [comment] 2018-06-03 09:18
@codeteo I could reproduce this behaviour with Apache 2.4. Underscores in names don't work, it does however work for Nginx

**Comment by cytopia** [comment] 2018-06-03 09:35
This can be resolved by adding the following option to apache global configuration:
```
HTTPProtocolOptions unsafe
```

I will make this default and let you know once its updated

**Comment by cytopia** [comment] 2018-06-03 10:11
FIx is on the way:

* https://github.com/devilbox/docker-apache-2.2/pull/10
* https://github.com/devilbox/docker-apache-2.4/pull/10

**Comment by cytopia** [comment] 2018-06-03 12:07
Try out PR and see if that fixes it: https://github.com/cytopia/devilbox/pulls

**Closed** 2018-06-07 05:59 UTC
Labels: bug, docker
