### ISSUE TITLE
Use .localhost as TLD_SUFFIX 

### ISSUE THREAD

**Issue by sakonn** [cytopia/devilbox#198] opened 2018-02-22 11:16 UTC
Hello, 
I wanted to switch my local projects to .localhost because chromium is no longer supporting .dev domain. When I change hosts in `etc/hosts` file and **TLD_SUFFIX** in `docker-compose.yml` Devilbox starts but Bind service will crash. Virtual hosts shows problem but i can acess my local sites but response time is much longer.

![screenshot from 2018-02-22 12-14-11](https://user-images.githubusercontent.com/17552397/36535468-08450bea-17ca-11e8-981d-aa562fe87b75.png)
My log:
```
bind_1   | root $ echo 'include "/etc/bind/custom-named.conf.localhost";' >> /etc/bind/named.conf
bind_1   | [INFO] Adding custom DNS forwarder: 8.8.8.8,8.8.4.4
bind_1   | [INFO] Starting BIND 9.10.3
devilbox_bind_1 exited with code 1
```

**Comment by cytopia** [comment] 2018-02-22 12:04
Are you using the latest update from devilbox git branch?

**Comment by sakonn** [comment] 2018-02-22 12:09
I updated project before creating issue. I use latest master files.

**Comment by cytopia** [comment] 2018-02-28 11:44
What operating system and docker/docker-compose versions are you using?

**Comment by cytopia** [comment] 2018-03-05 22:12
@sakonn I have reproduced this bug. Looks like it is not fixable for me. The bundled bind server is using a catch-all for the domain, however when doing catch-all for `localhost`, every request ends up on `localhost` instead of resolving `localhost` to some IP address. So I guess you will have to pick a different `TLD_SUFFIX`.

**Closed by cytopia** 2018-03-05 22:12 UTC
Labels: bug, wontfix
