### ISSUE TITLE
devilbox on ubuntu 20, localhost not responding anymore

### ISSUE THREAD

**Issue by garethjax** [cytopia/devilbox#723] opened 2020-09-10 12:26 UTC
### ISSUE TYPE

 - Bug Report

### Checklist

* [x] `.env` file is attached
[_env.zip](https://github.com/cytopia/devilbox/files/5201458/_env.zip)

* [ ] `docker-compose.override.yml` is attached (if it exists)
* [ ] Custom configs from `cfg/` dir are attached (if customized)
* [x] `docker-compose logs` and `log/` output is added
[log.zip](https://github.com/cytopia/devilbox/files/5201466/log.zip)
[dockerllogs.txt](https://github.com/cytopia/devilbox/files/5201494/dockerllogs.txt)

* [x] I've looked through the docs: https://devilbox.readthedocs.io/en/latest/
* [x] I've looked through existing issues: https://github.com/cytopia/devilbox/issues
* [x] I've read troubleshooting: https://devilbox.readthedocs.io/en/latest/support/troubleshooting.html

### OS / ENVIRONMENT

1. Host operating system and version:  Pop!_OS 20.04 LTS (ubuntu)
2. (Windows) Native Docker or Docker Toolbox: 
3. Docker version: 19.03.12
4. Docker Compose version: 1.25.5 
5. (Linux) Is SELinux enabled?: no
6. What git commit hash are you on?:  3556873f1920790b22a1d686966c689e2e2d4017 (1.7.1)

### SUMMARY

I have another folder with an older devilbox install (around 2019) which i've used for several dev projects. I've tried to update it and it has stopped working. So, I have tried to reinstall Devilbox in a different folder: i've followed the exact guidelines listed inside readthedocs, but the localhost does not shows the usual interface anymore. I've even tried to change http port to 8086 to avoid interference with other services.

### STEPS TO REPRODUCE

I just launch "docker-compose up php mysql httpd redis bind" and then try to open the standard homepage in Firefox http://localhost or https://localhost or https://localhost:8086. 
The result is always a connection error.

### EXPECTED BEHAVIOUR

The usual devilbox interface, showing the active services, should be displayed.

### ACTUAL BEHAVIOUR

404 page not found

### OTHER INFORMATION
If i connect to the php container, using shell.sh, I'm unable to resolve any address (eg: ping www.google.com does not work).

#### Start command

```
$  "docker-compose up php mysql httpd redis bind" 
```

#### File and user permissions (Linux & MacOS)

```
$ id 

uid=1000(garethjax) gid=1000(garethjax) gruppi=1000(garethjax),4(adm),27(sudo),107(input),118(lpadmin),1003(docker)

```

```
$ ls -la

drwxrwxr-x  2 garethjax garethjax  4096 set  9 22:40 autostart
-rwxr-xr-x  1 garethjax garethjax    56 set 10 11:23 avvia.sh
drwxr-xr-x  3 garethjax garethjax  4096 set  9 23:07 backups
drwxrwxr-x  2 garethjax garethjax  4096 set  9 22:40 bash
drwxrwxr-x  2 garethjax garethjax  4096 set  9 23:07 ca
drwxrwxr-x 57 garethjax garethjax  4096 set  9 22:40 cfg
-rw-rw-r--  1 garethjax garethjax  8874 set  9 22:40 CHANGELOG.md
drwxrwxr-x  2 garethjax garethjax  4096 set  9 22:40 compose
-rw-rw-r--  1 garethjax garethjax  2770 set  9 22:40 CONTRIBUTING.md
drwxrwxr-x  3 garethjax garethjax  4096 set  9 22:40 data
drwxrwxr-x  3 garethjax garethjax  4096 set  9 22:40 .devilbox
-rw-rw-r--  1 garethjax garethjax   747 set  9 22:40 docker-compose.override.yml-example
-rw-rw-r--  1 garethjax garethjax 14932 set  9 22:40 docker-compose.yml
-rw-rw-r--  1 garethjax garethjax 33244 set 10 14:11 dockerllogs.txt
drwxrwxr-x 20 garethjax garethjax  4096 set  9 22:40 docs
-rw-rw-r--  1 garethjax garethjax  2502 set  9 22:40 .editorconfig
-rw-rw-r--  1 garethjax garethjax 18916 set 10 14:10 .env
-rw-rw-r--  1 garethjax garethjax 18914 set 10 11:43 _env
-rw-rw-r--  1 garethjax garethjax 18914 set  9 22:40 env-example
-rw-rw-r--  1 garethjax garethjax  5947 set 10 14:05 _env.zip
drwxrwxr-x  8 garethjax garethjax  4096 set 10 14:11 .git
drwxrwxr-x  4 garethjax garethjax  4096 set  9 22:40 .github
-rw-rw-r--  1 garethjax garethjax  3643 set  9 22:40 .gitignore
-rw-rw-r--  1 garethjax garethjax  1064 set  9 22:40 LICENSE.md
drwxrwxr-x  4 garethjax garethjax  4096 set  9 23:07 log
-rw-rw-r--  1 garethjax garethjax  2510 set 10 14:06 log.zip
drwxrwxr-x  9 garethjax garethjax  4096 set  9 23:07 mod
-rw-rw-r--  1 garethjax garethjax 65197 set  9 22:40 README.md
-rw-rw-r--  1 garethjax garethjax    86 set  9 22:40 shell.bat
-rwxrwxr-x  1 garethjax garethjax    59 set  9 22:40 shell.sh
drwxrwxr-x  5 garethjax garethjax  4096 set  9 22:40 .tests
-rw-rw-r--  1 garethjax garethjax 11506 set  9 22:40 .travis.yml
-rwxr-xr-x  1 garethjax garethjax    93 set 10 11:49 uccidi.sh
-rwxrwxr-x  1 garethjax garethjax  2265 set  9 22:40 update-docker.sh
-rw-rw-r--  1 garethjax garethjax  1857 set  9 22:40 UPDATING.md
```

```
$ ls -la data/www

drwxr-xr-x 2 garethjax garethjax 4096 set  9 22:40 .
drwxrwxr-x 3 garethjax garethjax 4096 set  9 22:40 ..
-rw-rw-r-- 1 garethjax garethjax    0 set  9 22:40 .keepme

```

Thanks for any insight!

**Comment by cytopia** [comment] 2020-11-12 18:25
@garethjax unfortunately I am unable to reproduce your issue. The integration tests (which cover all your steps) are run on Ubuntu 20 once a day and they all work fine. I assume you do have some local system issues.

You can give the new release v1.8.1 (https://github.com/cytopia/devilbox/pull/747) a try. It comes with `check-config.sh` which checks against common configuration issues and has various updates compared to your current version.

I will close this issue as it cannot be reproduced ubfortunately.

**Closed by cytopia** 2020-11-12 18:25 UTC
Labels: bug

**Comment by garethjax** [comment] 2020-11-14 09:43
Thanks for the effort, in the mean time i've migrated to using valet for my dev projects. It's not the same thing, but at least i'm able to keep working.
