### ISSUE TITLE
DNS problem (docker-toolbox \ Win7x64 \ non-admin user)

### ISSUE THREAD

**Issue by jayson-lynnfield-zen** [cytopia/devilbox#119] opened 2017-08-29 21:30 UTC
Hi, 
I've already complete setup & using devilbox tool on OS X 
(it means that i understand how it works fine)

But on **Windows7 x64** host i have a following issue.
Accordingly to documentation, we need to specify a "**LOCAL_LISTEN_ADDR**",
which is **127.0.0.1** by default. Docker tools software versions provided in attachment image.
In case of windows 7 we can use only **docker-toolbox**, and cannot use a **docker-native client**...
While it starts - it shows an IP **192.168.99.100** 
which must replace a default IP address (**127.0.0.1:**) from **.env** file.

Once I've set that - i'm launching the utility...
Starting procedure are the same as on OS X... 
The tool sequentially launches a few web services and goes to idle state...

Afterwards my browser (_Google chrome Version 60.0.3112.113 (Official Build) (64-bit)_) 
can't get to the main web-panel, neither one of following addresses are recognized by DNS 
_127.0.0.1
192.168.99.100
172.16.238.11
localhost_

I've tries to set all of them to "**LOCAL_LISTEN_ADDR**" value, 
each time after any changes being made I've erase all present containers through following commands:
_docker rm -f $(docker ps -a -q)
docker rmi $(docker images -q)_
for now it is still doesn't see web-panel...

Who is sharp enough, please advise - what it can be? Is there any solution for that?
Thanks for paying attention, good luck

Software versions are
![dockers ip](https://user-images.githubusercontent.com/26794208/29843577-ea280c38-8cfb-11e7-8305-bc42695d49dc.png)

Working idle state of devilbox tool
![idle-state](https://user-images.githubusercontent.com/26794208/29845886-131916c0-8d04-11e7-99a0-3fe01d39c890.png)

![localhost](https://user-images.githubusercontent.com/26794208/29845888-131b96ac-8d04-11e7-92a2-a3c49ea0f1b3.png)
![127001](https://user-images.githubusercontent.com/26794208/29845885-1318e088-8d04-11e7-8dda-12634ea40414.png)
![19216899100](https://user-images.githubusercontent.com/26794208/29845887-131b751e-8d04-11e7-8fc2-5f42f525fd03.png)
![1721623811](https://user-images.githubusercontent.com/26794208/29845884-131849de-8d04-11e7-8f3d-905917d3c3c1.png)

**Comment by cytopia** [comment] 2017-08-30 07:28
@jayson-lynnfield-zen unfortunately it is still doesn't support Docker Toolbox. If you have any change to use Windows 10, go for it, otherwise you will have to wait a bit, until I (or someone else) have found a way.

**Comment by jayson-lynnfield-zen** [comment] 2017-08-30 07:33
@cytopia thanks for reply

**Comment by cytopia** [comment] 2017-09-03 08:23
@jayson-lynnfield-zen 
Could you set `LOCAL_LISTEN_ADDR=127.0.0.1:` to `LOCAL_LISTEN_ADDR=` in `.env` and try to access it again?

**Comment by jayson-lynnfield-zen** [comment] 2017-09-03 10:50
You mean live it blank (empty)?

**Comment by jayson-lynnfield-zen** [comment] 2017-09-03 10:50
@cytopia you mean live it blank (empty)?

**Comment by jayson-lynnfield-zen** [comment] 2017-09-03 12:38
@cytopia, i've found one weird moment...
Once i've create internal service-dependent directories (_www, mysql, pgsql_ and _mongo_)
and then get starting devilbox-tool, this folders are not filling by any of temporary working files... is that normal state?

-- My first attempt was a blank address,
such like: _LOCAL_LISTEN_ADDR=_ **web-interface inaccessible** (output log in attachement)
![report](https://user-images.githubusercontent.com/26794208/30002922-d4368448-90a4-11e7-9449-ebc5543a7af5.png)

-- Then i've try to add a colon mark,
like that: _LOCAL_LISTEN_ADDR=:_ **fails to start**
-- Than i get rid of google's DNS (left only my own DNS Server), and tries to set the my own subnet address with colon-mark at the end, 
such as: _LOCAL_LISTEN_ADDR=192.168.0.0:_ **web-interface inaccessible**...
-- At the final attempt, i've set predefined ip (from router) **fails to start**

**Comment by cytopia** [comment] 2017-09-03 13:30
@jayson-lynnfield-zen can you paste the full log for httpd from your first try with an empty `LOCAL_LISTEN_ADDR` (no colon):
```
docker-compose up -d
docker-compose logs httpd
```

**Comment by jayson-lynnfield-zen** [comment] 2017-09-03 13:39
@cytopia yep, I'll send it, when get to the pc... 
Through 4-5 hours or so

**Comment by jayson-lynnfield-zen** [comment] 2017-09-03 19:20
@cytopia i've execute that,results are below
![report](https://user-images.githubusercontent.com/26794208/30005908-420182e8-90dc-11e7-8ae9-72c69d943107.png)

**Comment by cytopia** [comment] 2017-09-27 21:26
@jayson-lynnfield-zen I made a major rewrite to overcome some limitations. I hope I could also address your problems. Pull request is not merged yet (https://github.com/cytopia/devilbox/pull/130), however could you checkout the branch and give it a try:

1. just to make sure everything is reset
```
docker-compose down
docker-compose rm -f
```
2. Check out new branch
```
git fetch --all
git checkout REL-0.12
```
3. Compare new `env-example` with your local `.env`
```
vimdiff .env env-example
```
4. Start it up
```
docker-compose up -d
```
Hope it can fix some problems

**Comment by jayson-lynnfield-zen** [comment] 2017-09-27 21:28
Thanks man, I'll check it as fast as I can, write you later

Best regards, Jason E.

Отправлено из ProtonMail mobile

-------- Исходное сообщение --------
Вкл 28 сент. 2017 г., 2:26, cytopia написал(а):

**Comment by jayson-lynnfield-zen** [comment] 2017-09-28 15:13
@cytopia 
I've downloaded latest version, it gives an error right from starting... (See attached file)
i've set dns server to my own, than to Google's, afterwards i change IP to null, and to docker-toolbox IP with no any results. Firewall was disabled.
![output](https://user-images.githubusercontent.com/26794208/30974396-1ebbc280-a45f-11e7-93e5-da9e51ba53ea.png)

**Comment by cytopia** [comment] 2017-09-28 15:33
There seems to be two docker networks. One from your previous devilbox instance and the new one. However both do use the same IP.

So do the following (**First shutdown the devilbox**):
```shell
# show devilbox networks
docker network ls --filter 'name=devil*' 

# delete all networks starting by devilbox
docker network rm <network-name>
```

Alternatively use this command:
```shell
docker network rm $(docker network ls --filter 'name=devil*' -q | xargs)
```

That should fix your problems

**Comment by jayson-lynnfield-zen** [comment] 2017-09-28 15:52
@cytopia ok, I'll check it, thanks

Best regards, Jason E.

Отправлено из ProtonMail mobile

-------- Исходное сообщение --------
Вкл 28 сент. 2017 г., 20:33, cytopia написал(а):

**Comment by jayson-lynnfield-zen** [comment] 2017-09-29 10:04
@cytopia Yep, it was not so simple as i want,
but anyway, i did removed those networks, forcefully...
Afterwards i perform a clean start of devilbox...
on default IP (127.0.0.1) and on docker-machine IP (192.168.99.100) web interface were still inaccessible.
on service IP (172.16.238.11) it gives an error (can't assign requested address)

**Comment by cytopia** [comment] 2017-09-29 13:57
That means address or port is already in use on your side. Can you check what else is listening on the required ports on those IP addresses

**Comment by jayson-lynnfield-zen** [comment] 2017-09-30 03:06
@cytopia Can you advise, which command should i use for that checking?
basic netstat can show little bit more excess for security reasons...

also there's some outputs for executed commands...
Maybe this provide some help.

While IP is broadcasted (**LOCAL_LISTEN_ADDR=**)
- webUI not responding (sql & http logs are):
![broadcast](https://user-images.githubusercontent.com/26794208/31041524-9123a1d0-a586-11e7-9c6c-fa675b027958.png)

While IP is set to default (**LOCAL_LISTEN_ADDR=127.0.0.1:**)
- webUI not responding (sql & http logs are):
![127 0 0 1](https://user-images.githubusercontent.com/26794208/31041837-58d18d56-a58b-11e7-942a-b7e4844e306b.png)
and there's a bind log
![bind](https://user-images.githubusercontent.com/26794208/31041891-2edc1556-a58c-11e7-9a70-863135104070.png)

While IP belongs to docker (**LOCAL_LISTEN_ADDR=192.168.99.100:**)
- webUI not responding (sql & http logs are):
![192 168 99 100](https://user-images.githubusercontent.com/26794208/31041724-d40c7280-a589-11e7-927d-7876030a33f9.png)

While IP belongs to service itself (**LOCAL_LISTEN_ADDR=172.16.238.11:**)
- utility doesn't start at all (output as follows):
![172 16 238 11](https://user-images.githubusercontent.com/26794208/31041570-01c518ce-a587-11e7-9810-1862bd2d72a2.png)

**Comment by cytopia** [comment] 2017-09-30 06:19
@jayson-lynnfield-zen yes I can help :-)

You are using the `master` branch, however, all the fixes are currently not yet merged to master and are still in branch `REL-0.12`.

So as described above, checkout `REL-0.12`, compare the `env-example` with `.env` and start it up.

**Comment by jayson-lynnfield-zen** [comment] 2017-10-07 12:39
Hi, sorry for long responding...
You asking to check address and ports,
Which command should I use for that?
I'm about flags, or args of netstat...
Also my local IP, for that particular case, is 192.168.5.129
Thanks

Best regards, Jason E.

Отправлено из ProtonMail mobile

-------- Исходное сообщение --------
Вкл 30 сент. 2017 г., 11:19, cytopia написал(а):

**Comment by cytopia** [comment] 2017-10-07 16:18
Looks like the port assigned to bind in `.env` is already taken.

* Alter the bind port in `.env`
* Checkout above mentioned branch `REL-0.12`
* Start up again (try only with `httpd`, `bind` and `php`)

**Comment by jayson-lynnfield-zen** [comment] 2017-10-10 08:41
@cytopia I've finally got my windows-desktop, and apply REL-0.12 branch...
I've made a clean install, .env file being created right from your new env-example file...

first attempt with no any address specified (broadcasted):
localhost, 127.0.0.1, 172.16.238.11 are not responding
**192.168.99.100** got step forward... it gave me a **404 error**...

second attempt was with docker ip specified (192.168.99.100:)
**404 on 192.168.99.100**, others not responding

third time I've set **127.0.0.1:** value (as in your default version)
all addresses are not responding

Then I've set a broadcast address again, change BIND port to **3000** (1053 was initially being set), and there's my logs-output
![output](https://user-images.githubusercontent.com/26794208/31377163-ab684b6e-ad96-11e7-8603-217ae61bc2ce.png)
no responds from any address were found ((

**Comment by jayson-lynnfield-zen** [comment] 2017-10-10 08:43
@cytopia and there's output from logs httpd & bind services
![output](https://user-images.githubusercontent.com/26794208/31377300-15f78030-ad97-11e7-8288-39261be404ee.png)
5.39 is router

**Comment by cytopia** [comment] 2017-10-10 09:49
@jayson-lynnfield-zen 

I think, the only way to go from your debugging is:

1. `LOCAL_LISTEN_ADDR=` (empty, so it listens on all address)
2. Open URL: `http://192.168.99.100`

This leads to a `404`, the furthest you got.

So can you paste the httpd error log from nginx here after you made a request to `http://192.168.99.100`

**Comment by jayson-lynnfield-zen** [comment] 2017-10-11 05:12
@cytopia correct me if i wrong...
_httpd error log_ called by **docker-compose logs httpd** command right?

there's a log right after utility being started (
![afterstart](https://user-images.githubusercontent.com/26794208/31423154-6d408b56-ae42-11e7-8a39-277e127e1dd1.png)

and there's a log after i made a request... (seems all the same)
![afterrequest](https://user-images.githubusercontent.com/26794208/31423175-8ce5d056-ae42-11e7-88ef-c3aa984fde71.png)

**Comment by cytopia** [comment] 2017-10-11 06:41
@jayson-lynnfield-zen No. I mean the physical log file inside the `./log/nginx-stable/` folder.

**Comment by jayson-lynnfield-zen** [comment] 2017-10-11 06:57
@cytopia in my case log folder has only one, single file, called .keepme

**Comment by cytopia** [comment] 2017-10-11 07:02
@jayson-lynnfield-zen there must be something as soon as the devilbox starts. Could you do the following and paste the folder structure here:
```shell
ls -lR log/
```

**Comment by jayson-lynnfield-zen** [comment] 2017-10-11 07:04
@cytopia 
![testt](https://user-images.githubusercontent.com/26794208/31426331-6adfc86c-ae52-11e7-8180-736a41b72044.png)

**Comment by cytopia** [comment] 2017-10-11 07:04
@jayson-lynnfield-zen 
You could also quickly join the gitter chat. I have a few more minutes before I have to leave: https://gitter.im/devilbox/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by cytopia** [comment] 2018-03-05 22:22
As discussed on gitter,  I will close it and mark it as wont fix

**Comment by aozkan** [comment] 2018-04-16 18:04
Hi, Was there a solution to this issue?  It is identical to the problems I'm having using Windows 7.

**Comment by prototype2118** [comment] 2018-10-25 14:52
Same issue as above.  404 nginx error on windows 10 home edition.  I have to use Docker Toolbox and nothing is being created in the devilbox folders.

**Comment by cytopia** [comment] 2018-10-26 07:46
I will re-open this issue as it seems to be active again. @aozkan @prototype2118 please provide detailed information about your system and how to reproduce this issue, so I can start debugging this.

**Comment by prototype2118** [comment] 2018-10-31 15:18
Same issue as described above.  I use Docker Toolbox on a Windows 10 Home Edition laptop and can compose up to create the container.  Going to the IP address of the container brings me directly to the 404 nginx page. I cannot get to the devilbox admin page.

**Comment by cytopia** [comment] 2018-11-01 09:10
@prototype2118 

> Going to the IP address of the container brings me directly to the 404 nginx page

How did  you get the IP address of the container? Did you have a look here: https://devilbox.readthedocs.io/en/latest/howto/docker-toolbox/find-docker-toolbox-ip-address.html#howto-find-docker-toolbox-ip-address

**Comment by prototype2118** [comment] 2018-11-01 13:06
> @prototype2118
> 
> > Going to the IP address of the container brings me directly to the 404 nginx page
> 
> How did you get the IP address of the container? Did you have a look here: https://devilbox.readthedocs.io/en/latest/howto/docker-toolbox/find-docker-toolbox-ip-address.html#howto-find-docker-toolbox-ip-address

The IP address of the container was shown upon startup.  It's the same IP address in the link you provided.

**Comment by cytopia** [comment] 2018-11-01 14:10
@prototype2118 can you attach your `.env` file.

**Comment by cytopia** [comment] 2018-11-04 06:55
There's an upcoming PR which is going to mitigate DNS issues on Docker Toolbox (Windows and MacOS): https://github.com/cytopia/devilbox/pull/411

Please have a look and let me know how this works for your.

**Comment by cytopia** [comment] 2018-12-31 09:13
@jayson-lynnfield-zen @aozkan  @prototype2118 


I have removed `wontfix` as development for this is already in progress.

This ticket is now a duplicate of: https://github.com/cytopia/devilbox/issues/248

I will therefore close this one and all further discussions should continue here: https://github.com/cytopia/devilbox/issues/248

**Closed by cytopia** 2018-12-31 09:13 UTC
Labels: DNS, bug, duplicate, host:virtualbox (docker-toolbox)
