### ISSUE TITLE
Wordpress - Unable to establish secure connection

### ISSUE THREAD

**Issue by idpocky** [cytopia/devilbox#174] opened 2018-01-03 07:37 UTC
After the installation of Wordpress, I got the warning message while entering the wp-Admin:
```
...
Unable to establish secure connection with *wordpress.org*...
...
```
Please help...

---

+ Bind(9.10.3-)
+ PHP(7.1.9)
+ nginx(1.12.1)
+ MariaDB(10.2.8)

I am on the 'DVL-013-fix-dns' branch.

**Comment by mrpsiho** [comment] 2018-01-03 07:39
Yes, I receive the same message from time to time. Also, the information about updates of WP plugins is not available in the admin area of the site. Looks like these requests just blocked somehow.

**Comment by mrpsiho** [comment] 2018-01-03 07:41
<img width="840" alt="screen shot 2018-01-03 at 9 40 12 am" src="https://user-images.githubusercontent.com/2705129/34512300-21624958-f06a-11e7-918b-35e1ae6a882d.png">
One may think that version 3.1 is the latest for WooCommerce plugin, but that's not true. The information about available updates is just blocked :(

**Comment by cytopia** [comment] 2018-01-03 09:43
Could you guys have a look at the Chrome/Firefox console while doing this request. There might be some errors visible why this connection does not work.

**Comment by idpocky** [comment] 2018-01-03 10:02
Checked...No errors in the console.

I think that user will get this warning message while visiting those pages (plugins, themes...)  which need to connect `api.wordpress.org`. It means that the `httpd server` need to be able to connect `api.wordpress.org`.

Some topics about this `warning message` suggested that user need to edit the `/etc/hosts` to add this line: 

```
# xx.xx.xx.xx is the ip you get by ping
xx.xx.xx.xx  api.wordpress.org
```

**Comment by cytopia** [comment] 2018-01-03 10:27
@idpocky  the `PHP` server will be responsible for doing those requests. Could you enter it and try to curl `api.wordpress.com`:

```
./shell.sh
curl api.wordpress.com
```

**Comment by idpocky** [comment] 2018-01-03 10:46
Yes, Tried and curl is ok.

Finally, I tried to add the line ` 66.155.40.189 api.wordpress.org` to the `/etc/hosts`...
Ok, the warning message is no longer appear. I can get the tip of plugin updating too.

But I think it will be great if `devilbox` can do it automatically 😄.

**Comment by cytopia** [comment] 2018-01-03 10:55
What does the following command output 1. on your host system and 2. inside the PHP-FPM container:
```
host api.wordpress.org
```

**Comment by idpocky** [comment] 2018-01-03 10:55
Sorry, The line should be `66.155.40.189 wordpress.org`.
Otherwise, the `plugin-install` page will get error while getting the available plugin list.

**Comment by cytopia** [comment] 2018-01-03 10:57
```
$ host wordpress.org
wordpress.org has address 66.155.40.249
wordpress.org has address 66.155.40.250
```
If you need to change the domain `wordpress.org` to something else in order to get wordpress working, then there is something wrong with wordpress or its plugins itself.

**Comment by idpocky** [comment] 2018-01-03 11:01
```
devilbox@php-7.1.9 in /etc $ host api.wordpress.org
api.wordpress.org has address 66.155.40.188
api.wordpress.org has address 66.155.40.249
api.wordpress.org has address 66.155.40.189
api.wordpress.org has address 66.155.40.203
api.wordpress.org has address 66.155.40.187
api.wordpress.org has address 66.155.40.186
api.wordpress.org has address 66.155.40.250
api.wordpress.org has address 66.155.40.202

devilbox@php-7.1.9 in /etc $ host wordpress.org
wordpress.org has address 66.155.40.249
wordpress.org has address 66.155.40.250
```

Yes, I think so.

**Comment by idpocky** [comment] 2018-01-03 11:09
I recovered the `hosts file`, and it works normally now.
Thanks!

**Comment by mrpsiho** [comment] 2018-01-03 12:31
@idpocky sorry, you did what? could you explain what you did in order to work it ok? Thanks!

**Comment by idpocky** [comment] 2018-01-04 03:50
@mrpsiho I did 2 things:

+ I edited the `/etc/hosts` and added a new line `66.155.40.189 wordpress.org` by `$ ./shell.sh`.
+ I recovered `/etc/hosts` by removing the line added above.

Technically, I did nothing. So ... maybe the reason I got the warning message was due to my internet access problem. After recovering, It works normally.

As @cytopia said, I think the wordpress should be ok if you can connect `wordpress.org` by your docker container. Otherwise, It must be something wrong with the wordpress service.

**Comment by mrpsiho** [comment] 2018-01-04 05:21
@idpocky thanks!
@cytopia without such additional line in `/etc/hosts` it works like that in my case:
- sometimes - quite rarely - I see the information about the updates and do not see that warning mentioned here above
- I try to update a plugin and ends up with this
<img width="626" alt="screen shot 2018-01-04 at 7 10 09 am" src="https://user-images.githubusercontent.com/2705129/34551077-e5b68b34-f11e-11e7-9807-abd38429c188.png">
- however, the plugin is actually updated after that, but then still no info for other plugins:
<img width="576" alt="screen shot 2018-01-04 at 7 11 20 am" src="https://user-images.githubusercontent.com/2705129/34551094-0d55b674-f11f-11e7-8ef4-5fc1e4075032.png">

And now I added `66.155.40.189 wordpress.org` to `/etc/hosts` of my php container, but it seems have no effect for me. I see the same as on my second screenshot.

**Comment by mrpsiho** [comment] 2018-03-13 06:23
It seems like this issue is related to my laptop or ISP I use. Or... I don't know... I have noticed when less tabs in the browser are opened - it works fine for me, no issues.
Anyway, I don't think it is related to devilbox.

**Comment by cytopia** [comment] 2018-03-13 06:29
@mrpsiho ok I will close this issue then. FYI: You should give the new PHP container a try (will be merged once I have enough feedback): https://github.com/cytopia/devilbox/pull/203

**Closed by cytopia** 2018-03-13 06:29 UTC

**Comment by adammarton** [comment] 2018-05-29 09:16
The issue still persists on my env (Windows 10, Docker 18.03.1-ce-win65 (17513)).

**Comment by zloymalefic** [comment] 2020-07-09 07:46
The same for me, there is no any plugins, just pure Wordpress and the issue is reproduced
