### ISSUE TITLE
Disable caching?

### ISSUE THREAD

**Issue by janschoepke** [cytopia/devilbox#300] opened 2018-07-04 11:38 UTC
Is there any possibility to completely disable Opcache and other caching mechanisms? This would be very helpful for development.

**Comment by cytopia** [comment] 2018-07-04 11:58
Yes, you can disable (unload) any modules for PHP: https://devilbox.readthedocs.io/en/latest/configuration-files/env-file.html#php-modules-disable

To unload opcache, add the following to `.env`
```
PHP_MODULES_DISABLE=opcache
```

You could also use php.ini directives to still load the module itself, but disable it.
https://devilbox.readthedocs.io/en/latest/configuration-files/php-ini.html

**Comment by janschoepke** [comment] 2018-07-04 12:04
Thanks for the quick reply. I thought that the error I'm getting comes from Opcache. I installed the shopware eCommerce system in a container. The installation worked perfectly fine. When accessing the frontend of the shop, it is nearly impossible to navigate through the CMS.  Every second page-call results in a blank page, sometimes the old page content is displayed despite the changed URL. Parallel to the installation in devilbox I did an installation in XAMPP, everything works fine there. What could this be?

**Comment by cytopia** [comment] 2018-07-04 12:08
1. Are you on Windows, Linux or Mac?
2. If Windows or Mac, are you using native Docker or Docker Toolbox?
3. How long is the timeout until you see the page or the white page?
4. Did you get any error logs under `./log/nginx-*|apache-*` and `php-fpm-*.*`?

**Comment by janschoepke** [comment] 2018-07-04 12:34
1. Linux (Ubuntu 16.04 LTS)
2. see 1
3. the blank page is being rendered instantly (~200ms)
4. apache-log und php-fpm-log: only entries in access log.

**Comment by cytopia** [comment] 2018-07-04 12:37
Any error visible via
```
docker-compose logs httpd
docker-compose logs php
```
Does the blank code has any HTTPD status code attached? 2XX, 3XX, 4XX or 5XX?

**Comment by janschoepke** [comment] 2018-07-04 12:52
No errors in the response of given commands, HTTP status of blank page says 200 OK.

**Comment by cytopia** [comment] 2018-07-05 07:13
@janschoepke can you provide a link to the CMS you have installed as well as your installation steps. I will try to reproduce this error

**Comment by janschoepke** [comment] 2018-07-05 07:55
Sure: 
I've installed Shopware eCommerce CMS (http://shopware.com) in latest version (5.4.5). 
The direct download link: [Download](http://releases.s3.shopware.com.s3.amazonaws.com/install_5.4.5_6847c0845f0f97230aa05c7294fa726a96dda3ff.zip?_ga=2.213731798.356053871.1530772798-165429886.1517389227&_gac=1.123954552.1528448247.CjwKCAjw0ujYBRBDEiwAn7BKt5jreInmqLvDIBNYenclxA2XhdokekkhmWZcjRIDr-q2Cc-5_EPNbBoCOdUQAvD_BwE)

After setting up a new vhost and copying the install files into the htdocs folder, I called the url specified in vhosts (in my example http://sw-5-4-5.loc). The installation routine works perfectly fine, also the database connection is set up correctly (the installation routine creates a bunch of tables in the database). After completing the setup, the installer provides a link to the shop frontend. In the frontend you can find a dropdown menu in the upper right corner. The links provided there are mostly local shopsites. Navigating through them sometimes provides the described blank page. 
Is this description all you need?

**Comment by cytopia** [comment] 2018-07-05 08:59
I have re-created your setup.

I am using Apache 2.4 and PHP 7.2. It works fine over http and https.

* Front-end pages are loaded in around 500-900ms. (opcache disabled)
* Front-end pages are loaded in around 400ms. (opcache enabled)

No errors in Chrome console and no errors in Apache logs

```
OS:             Debian stretch
Docker:         18.05.0-ce, build f150324
Docker Compose: 1.19.0, build 9e633ef

CPU: Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
RAM: 16 GB
```

1. What PHP/Web server versoins are you using?

2. What are the hardware specs of your local computer/notebook

**Comment by janschoepke** [comment] 2018-07-05 09:31
```
PHP_SERVER=5.6
HTTPD_SERVER=apache-2.4
```
Local Machine:
```
OS: Ubuntu 16.4 LTS
Docker: 18.03.1-ce, build 9ee9f40
Docker Compose: 1.17.0, build ac53b73
CPU: Intel® Core™ i7-7500U CPU @ 2.70GHz × 4 
RAM: 16GB
```

**Comment by cytopia** [comment] 2018-07-05 10:20
I was able to reproduce this behaviour.

For now it seems to be specific to the following combinations:

*  `Apache 2.4` and `PHP 5.6`

Which combinations work:

* `Apache 2.2` and `PHP 5.6`
* `Apache 2.4` and `PHP 7.2`

**Comment by janschoepke** [comment] 2018-07-05 10:31
Thats a great message! 
Yesterday I got this described behavior when testing with an older version of shopware, which needed PHP 5.6 to run. 
Do you think this is a problem with Devilbox or with the Shop CMS?

**Comment by cytopia** [comment] 2018-07-05 10:34
Not exactly sure yet. If this behaviour can be reproduced with any other PHP 5.6 Container and Apache 2.4 then its shop related.

However, neither PHP nor Apache are throwing errors atm (I enforced errors to show up via `php_admin_value|flag`), so my first guess would be the Shop CMS (but that's not for sure).

I am currently trying out a few settings in Apache 2.4 and PHP 5.6 to see if this can be addressed via different default config

**Comment by cytopia** [comment] 2018-07-05 10:34
I suppose for now you can safely switch to Apache 2.2 and still keep PHP 5.6

**Comment by cytopia** [comment] 2018-07-07 08:44
I have tried even more custom vhost configurations, but still no positive result.

Your final choice would be to use any **other** combination than **Apache 2.4 and PHP 5.6**.

As this only affects Shopware so far (I have tested various other frameworks with the same combination and they all work), I would suggest to open up a ticket at their place as well.

For now I will close this issue as WON'T DO

**Closed by cytopia** 2018-07-07 08:44 UTC
Labels: question

**Comment by cytopia** [comment] 2018-07-07 09:14
https://devilbox.readthedocs.io/en/restructure-documentation/examples/setup-shopware.html

**Comment by janschoepke** [comment] 2018-07-09 12:40
Sorry for the late reply. Thank you for your effort and the entry in the documentation. We will use Devilbox in our company now. :)

**Comment by cytopia** [comment] 2018-07-09 13:58
Thanks for the feedback.
