### ISSUE TITLE
Howto: Using different PHP versions per project within Console/CLI

### ISSUE THREAD

**Issue by fkaminski** [cytopia/devilbox#951] opened 2023-01-17 17:31 UTC
### Have you already checked elsewhere?

- [X] I have read the [Devilbox documentation](https://devilbox.readthedocs.io/en/latest/)
- [X] I have checked the [Devilbox Troubleshooting Guide](https://devilbox.readthedocs.io/en/latest/)
- [X] I have checked the [Devilbox FAQ](https://devilbox.readthedocs.io/en/latest/support/faq.html)
- [X] I have checked the [Devilbox Howto](https://devilbox.readthedocs.io/en/latest/support/howto.html)
- [ ] I have checked the [Devilbox Forum](https://devilbox.discourse.group/)
- [X] I have checked [existing issues](https://github.com/cytopia/devilbox/issues)
- [ ] I have googled already with no luck
- [ ] I have not done any of the above

### What are you struggling with?

I am testing the release 3 with several PHP versions.
Default is PHP 7.4 and for two projects then individually with PHP 8.2. 

Just wondering how I can then achieve the correct PHP CLI version on the console for the appropriate project(s)?

### What have you tried already?

So far (with one global PHP version) I have simply used the existing shell.sh/shell.bat.

### What is your goal?

How can I achieve the correct PHP CLI version on the console for the appropriate project(s)?

**Comment by Ernestopheles** [comment] 2023-01-17 18:29
`docker-compose exec --user devilbox php74 bash -l`

leads to `devilbox@php74:/var/www/html$ `

php is 7.4;

from there you could navigate to shared/httpd

BUT no idea if thats a good way...

**Comment by Ernestopheles** [comment] 2023-01-19 14:17
For Linux:
This script may be used for a restart of devilbox with a backend and a start an according shell; unfortunately the last command is not executed; maybe s.b. can help here?

(Change path to devilbox for your IDE, please)

`#! /bin/bash
#
# Stop devilbox and remove containers
#
cd ~/webdev/devilbox || exit
docker-compose stop
docker-compose rm -f

# start devilbox with a php7.4 backend 
#
docker-compose up -d httpd php mysql bind php74

# Any project without a .devilbox/backend.cfg will run under the php-version selected in .env.
#
# Any project with a .devilbox/backend.cfg with entry 
#              conf:phpfpm:tcp:php74:9000 
# will run under php7.4.

# Start a devilbox shell with php7.4
#
docker-compose exec --user devilbox php74 bash -l

# Change to projects-dir (not working like so...)
#
cd /shared/httpd || exit`

**Comment by Ernestopheles** [comment] 2023-01-29 19:49
A look into shell.bat has been quite helpful. So this will work:

 # Start a devilbox shell with php7.4
#
docker-compose exec --user devilbox php74 bash -c "cd /shared/httpd; exec bash -l"

**Comment by cytopia** [comment] 2023-01-31 15:16
One could also do:
```
docker-compose exec php74 bash
su - devilbox
cd /shared/httpd
```

However, this is just normal `docker compose` usage, so I will close this.

**Closed by cytopia** 2023-01-31 15:16 UTC
Labels: question, Community help wanted

**Comment by TheoD02** [comment] 2023-02-10 16:54
Hey all !

Wanted to know how can i use composer in second PHP version ?

Configuration:
PHP 8.2 is the main in .env PHP_VERSION

And have PHP 7.4 for alternative projects that run on that version.

Context : 
I can run this project on web with 7.4 version with backend.cfg
I can run the CLI with PHP 7.4 but cannot have access to composer or yarn for example just php

Alternative i use now is to change the PHP_VERSION for the CLI and the current composer i want to use, the problem is when i work on two projects having 2 differents version i need to change, restart devilbox frequently

Thank ! 😄
